export type User = {
  id: string;
  name: string;
  email: string;
  role: "student" | "admin";
  email_verified: boolean;
};
export type Auth = { user: User; csrf_token: string };
export type Evidence = {
  value: unknown;
  source: string;
  document_id?: string;
  page?: number;
  snippet: string;
  confidence: number;
  verified?: boolean;
  corrected_at?: string | null;
  original_value?: unknown;
};
export type Criterion = {
  id: string;
  category: string;
  title: string;
  description: string;
  criterion_type: string;
  key: string;
  operator: string;
  required_value: unknown;
  unit: string;
  mandatory: boolean;
  weight: number;
  source_text: string;
  source_page: number | null;
  source_url: string | null;
  confidence: number;
  admin_verified: boolean;
  children: Criterion[];
};
export type Evaluation = {
  criterion: Criterion;
  status: "SATISFIED" | "NOT_SATISFIED" | "MISSING_EVIDENCE" | "UNCERTAIN" | "NOT_APPLICABLE";
  reason: string;
  evidence: Evidence[];
  confidence: number;
  score: number;
};
export type Category = { score: number | null; weight: number; evaluated: number; method: string };
export type Action = {
  title: string;
  description: string;
  priority: string;
  category: string;
  criterion_id: string;
  evidence: Evidence[];
  impact?: number;
  urgency?: number;
  feasibility?: number;
  priority_score?: number;
  deadline?: string;
  historical?: boolean;
};
export type Result = {
  eligibility: string;
  overall_score: number;
  categories: Record<string, Category>;
  evaluations: Evaluation[];
  strengths: Action[];
  gaps: Action[];
  recommendations: Action[];
  documents_complete: number;
  documents_required: number;
  critical_gaps: number;
  scoring_coverage: number;
  days_remaining: number | null;
  closed: boolean;
  disclaimer: string;
  score_method: string;
};
export type Scholarship = {
  id: string;
  name: string;
  data: {
    university?: string;
    country?: string;
    degree_level?: string;
    field?: string;
    deadline?: string;
    funding_type?: string;
  };
  source_text: string;
  source_url: string | null;
  source_type: string;
  status: string;
  error: string | null;
  active: boolean;
  version: number;
  created_at: string;
  weights: Record<string, number>;
  requirements?: { id: string; data: Criterion; admin_verified: boolean; version: number }[];
};
export type Analysis = {
  id: string;
  scholarship_id: string;
  version: number;
  status: string;
  progress: number;
  error: string | null;
  created_at: string;
  snapshot: {
    scholarship: Scholarship["data"] & {
      id: string;
      name: string;
      source_url: string | null;
      source_type: string;
    };
    profile: Profile;
    profile_version: number;
    as_of: string;
    documents: { id: string; filename: string; version: number }[];
    model_metadata: { provider: string };
    weights: Record<string, number>;
  };
  result: Result;
};
export type Fact = {
  id: string;
  key: string;
  value: unknown;
  original_value: unknown;
  page: number;
  snippet: string;
  confidence: number;
  verified: boolean;
  corrected_at: string | null;
};
export type Document = {
  id: string;
  filename: string;
  document_type: string;
  mime_type: string;
  file_size: number;
  page_count: number;
  status: string;
  progress: number;
  error: string | null;
  created_at: string;
  version: number;
  extraction: Record<string, unknown>;
  facts?: Fact[];
};
export type Profile = {
  full_name?: string;
  nationality?: string;
  country_of_residence?: string;
  date_of_birth?: string | null;
  university?: string;
  degree?: string;
  field_of_study?: string;
  gpa?: number | null;
  gpa_scale?: number;
  graduation_date?: string | null;
  graduation_year?: number | null;
  english_test?: string;
  english_score?: number | null;
  test_date?: string | null;
  skills?: string[];
  research?: string[];
  experience?: string[];
  courses?: string[];
  target_degree?: string;
  target_fields?: string[];
  preferred_countries?: string[];
  ai_enabled?: boolean;
};
export type Task = {
  id: string;
  analysis_id: string;
  data: Action;
  status: "Not Started" | "In Progress" | "Completed";
};
export type ChatMessage = {
  id: string;
  data: {
    question: string;
    status: string;
    answer?: string;
    mode?: string;
    sources?: {
      id: string;
      title: string;
      requirement?: string;
      evidence?: Evidence[];
      text?: string;
      reason?: string;
    }[];
  };
};
export type Simulation = {
  qualitative_method?: string;
  label: string;
  changes: Record<string, unknown>;
  current_score: number;
  simulated_score: number;
  difference: number;
  categories: Record<string, Category>;
  current_categories: Record<string, Category>;
  eligibility: string;
  evaluations: Evaluation[];
  disclaimer: string;
};
